"""Re-execute source probes and reconstruct the learned contracts on CPU."""
import json
import uuid

from scripts.boundary_learning import fit_groups
from scripts.prepare_boundary_study import generate, probe, source_audit
from scripts.audit_boundary_study import load_prepared
from scripts.evaluate_reuse_ablation import read
from skillforge.schemas import SkillContract


def semantic(value):
    # UUID values are regenerated by Environment; preserve their within-record
    # identity links and validate their syntax rather than masking whole rows.
    identifiers = {}
    def walk(obj):
        if isinstance(obj, list):
            return [walk(v) for v in obj]
        if isinstance(obj, dict):
            result = {}
            for key, val in sorted(obj.items()):
                if key == "latency_ms":
                    continue
                if key in {"refund_id", "transaction_id"}:
                    uuid.UUID(val)
                    identifiers.setdefault(val, "generated-id-" + str(len(identifiers)))
                    result[key] = identifiers[val]
                else:
                    result[key] = walk(val)
            return result
        return obj
    return walk(value)


def audit(plan_path="configs/boundary-study.json"):
    plan, root, tasks, boundaries, preparation = load_prepared(plan_path)
    if [t.model_dump() for t in generate(plan)] != [t.model_dump() for t in tasks]:
        raise ValueError("dataset differs from frozen scenario generator")
    bundle = read(plan["bundle"])
    if source_audit(bundle) != read(root / "source-audit.json"):
        raise ValueError("legacy source intervention differs on replay")
    bases = {s["family"]: SkillContract.model_validate(s) for s in bundle["skills"]}
    stored = read(root / "training-probes.json")
    replayed = [probe(t, bases[t.family]) for t in tasks if t.split == "train"]
    if semantic(replayed) != semantic(stored):
        raise ValueError("training probe semantics differ on actual replay")
    if (root / "oracle-executions.json").exists():
        actual = [probe(t, bases[t.family]) for t in tasks if t.split in {"validation", "test"}]
        if semantic(actual) != semantic(read(root / "oracle-executions.json")):
            raise ValueError("oracle execution evidence differs on actual replay")
    for family, base in bases.items():
        groups, traces = fit_groups(base, replayed, plan["max_added_conditions"])
        if traces != boundaries["learning_traces"][family] or any(groups[g].model_dump() != boundaries["groups"][g][family] for g in "ABCD"):
            raise ValueError("learned boundary differs when refit on train evidence")
    return {"passed": True, "replayed_training_probes": len(replayed), "reconstructed_contracts": len(bases) * 4,
            "ignored_nondeterminism": "tool latency and syntactically valid generated UUID values; identity links preserved"}


if __name__ == "__main__":
    print(json.dumps(audit()))
